version: "3.8"
services:
  app:
    image: node:20.11-bookworm-slim
    command: npm start
    working_dir: /app
    user: node
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - '${DB_PORT}:5432'
